# Generated by Django 5.2.16 on 2026-07-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='resume',
        ),
    ]
